enum actionTypes {
    ISSUES_GET_REQUEST = "ISSUES/GET",
    ISSUES_GET_SUCCESS = "ISSUES/GET_SUCCESS",
    ISSUES_GET_ERROR = "ISSUES/GET_ERROR",

    STATUS_ISSUE_CHANGE = "ISSUE/STATUS_CHANGE",
    ORDER_ISSUES_CHANGE = "ISSUES/ORDER_CHANGE",

    URL_SET = "URL/SET",

    LOADING_SET = "LOADING/SET",
}

export default actionTypes;
